### ISSUE TITLE
Fable 2 and paket

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-templates#16]
Hi, I have a suggestion for the next version of fable template.
What if we could install paket as local dotnet tool?
If we could use the [new paket](https://www.nuget.org/packages/Paket/5.182.0-alpha001) that runs on dotnet core, we don't need mono anymore. 

If we could add `dotnet tool install` as a [postAction](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script), we might pull it of.

Something like 
```js
{"postActions": [
        {
            "actionId": "3A7C4B45-1F5D-4A30-959A-51B88E82B5D2",
            "args": {
                "executable": "dotnet",
                "args": "tool install  --tool-path \".paket\" Paket --version 5.182.0-alpha001 --add-source https://api.nuget.org/v3/index.json"
            },
            "manualInstructions": [
                {
                    "text": "Run dotnet tool install  --tool-path \".paket\" Paket --version 5.182.0-alpha001 --add-source https://api.nuget.org/v3/index.json"
                }
            ],
            "continueOnError": true,
            "description": "Add paket"
        }
    ]}
```

I'm happy to make a PR if approved.
Your thoughts?

**Comment by alfonsogarciacaro** [comment]
I'd love to remove the Mono dependency, although I'm still wary of the new local cli tools because it seems the current design is not final yet. Not sure, any thoughts on this? @MangelMaxime @forki @enricosada

**Comment by MangelMaxime** [comment]
> I'm still wary of the new local cli tools because it seems the current design is not final yet

I do agree, I think waiting for the final design could be a good thing. But I am no expert of what is related to dotnet :) So I will follow the decision of @forki and @enricosada as they are probably more inform on this subject.

**Comment by forki** [comment]
/cc @enricosada

I think we need to wait for project wide tools.

Maxime Mangel <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
14:58:

**Comment by nojaf** [comment]
@forki, could please elaborate? What do you mean with project wide tools?

**Comment by forki** [comment]
Currently these Tools are project specific as in fsproj. But we need them
to be repository wide

Florian Verdonck <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
17:32:

**Comment by forki** [comment]
Yes global tools exist as well. But I'm hoping for repo tools. But maybe
I'm just a dreamer

Florian Verdonck <notifications@github.com> schrieb am Mi., 3. Okt. 2018,
20:25:

**Comment by alfonsogarciacaro** [comment]
Local tools should be more or less the same as repo tools, the main problem right now is there's no easy way to manage the version. Seems MSFT is working on this, [more info here](https://github.com/dotnet/cli/issues/9782#issuecomment-410033494).

**Comment by enricosada** [comment]
Florian, global tool installed + hook is exactly how will work.
The hook work really well, no paket.exe in repo and `dotnet build` from clone works.

You can try it in https://github.com/enricosada/paket-netcore-testing-as-tool/blob/master/README.md#scenario-2-integration-with-sdk

The issue atm is paket .net core doesn't respect the web proxy. It's the only big issue I know (and is the same issue you'll get install with dotnet install). Happy to get help with that, otherwise I'll do it but in free time this weekend I hope


From mobile

--
Enrico Sada
@enricosada
________________________________

**Comment by enricosada** [comment]
As a note, the proposed already allow to pin paket version (best practice).

If someone can fix web proxy

From mobile

--
Enrico Sada
@enricosada
________________________________

**Comment by nojaf** [comment]
I see, so scenario two does seem to hit the sweet spot.
I've tried it in my own [sample project](https://github.com/nojaf/fable-docker/tree/remove-mono/sample) and it works out nicely.

**Comment by nojaf** [comment]
Closing this issue as simple fable package doesn't have paket anymore.
It is easy to install .NETCore paket and run `paket convert-from-nuget`.
