### ISSUE TITLE
Template for dotnet 3.1?

### ISSUE THREAD

**Issue by inouiw** [fable-compiler/fable-templates#27]
I have dotnet 3.1 installed. When I type `dotnet new -i Fable.Template::*` then the template cannot be found. At the url https://www.nuget.org/packages/Fable.Template only the 3.0 version is listed.

When will the version for dotnet 3.1 be released?

**Comment by inouiw** [comment]
If sb else has the problem, the quickstart from fable.io works:

git clone https://github.com/fable-compiler/fable2-samples
cd fable2-samples/browser  
npm install
npm start

**Comment by MangelMaxime** [comment]
Hello,

I am not sure of what is needed for that. 

I mean the templates target `netstandard2.0` which should be compatible for Dotnet 2 & 3 from what I know.

If you know what needs to be changed, can you please send a PR?

**Comment by naartjie** [comment]
@inouiw I know you filed this issue a while back, but I think it's the `*` that's the problem, as the shell tries to expand it. Try quoting it:

```sh
dotnet new -i `Fable.Template::*`
```

Or alternatively you can remove the version part all together:
```sh
dotnet new -i Fable.Template
```

If you can confirm that's the problem, I think this issue can be closed.

**Comment by MangelMaxime** [comment]
Closing this issue as a solution has been provided and it is an old one.
