### ISSUE TITLE
Include a "build for production" script in package.json

### ISSUE THREAD

**Issue by inputusernamehere** [fable-compiler/fable-templates#43]
It would be nice if package.json (and the readme) included a script to bundle the application, as mentioned here: https://fable.io/docs/your-fable-project/build-and-run.html

Edit: For example how about `"build": "dotnet fable src && webpack"`?

**Comment by MangelMaxime** [comment]
Hello @inputusernamehere 

That's a good idea, do you want to send a PR?

**Comment by inputusernamehere** [comment]
I opened a PR. Let me know if there is anything I should change!
