### ISSUE TITLE
Include a .gitignore file in the root directory

### ISSUE THREAD

**Issue by inputusernamehere** [fable-compiler/fable-templates#44]
I think it would be nice to include a minimal .gitignore file to exclude at least the following:

```
node_modules/
obj/
*.fs.js
```

Edit: I can see that there is a `.gitignore` file included in the Contents directory of the minimal template in this repo: https://github.com/fable-compiler/fable-templates/blob/master/minimal/Content/.gitignore

However this did not get included in my project after running these commands:

```
dotnet new -i Fable.Template
dotnet new fable
```

**Comment by Happypig375** [comment]
https://github.com/dotnet/templating/issues/823

**Comment by MangelMaxime** [comment]
This has been fixed by adding `<NoDefaultExcludes>true</NoDefaultExcludes>` tag.
