### ISSUE TITLE
Using the template with yarn

### ISSUE THREAD

**Issue by fremontmj** [fable-compiler/fable-templates#59]
I'd like to install dependencies with Yarn, but the template comes with an npm lock file, and Yarn complains about possible inconsistencies.

Do you have any suggestions?

Thanks much for this great system!

**Comment by MangelMaxime** [comment]
Hello @fremontmj,

you can convert the template to Yarn by deleting `package-lock.json` and then running `yarn install`.

Yarn will compute the dependencies as if the repository was a new one and generates its own lock file.

**Comment by fremontmj** [comment]
Thanks! I was concerned about potentially installing wrong package versions, but I won't worry now.
